"use client";

import { CheckCircle2Icon, CheckIcon, LoaderCircleIcon, TriangleAlertIcon } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  ActionableNoteItemCard,
  type ActionableNoteItemUpdate,
} from "@/modules/meeting-details/components/ActionableNoteItemCard";
import type { ActionableNotes } from "@/modules/meetings/types/meeting.types";

interface ActionableNotesReviewPanelProps {
  notes: ActionableNotes;
  /** Transcript chunk ids rendered on this page, so evidence links resolve to an anchor. */
  resolvableEvidenceChunkIds: ReadonlySet<string>;
  onUpdate: (itemId: string, update: ActionableNoteItemUpdate) => Promise<void>;
  onFinish: () => Promise<void>;
  isSaving: boolean;
}

export function ActionableNotesReviewPanel({
  notes,
  resolvableEvidenceChunkIds,
  onUpdate,
  onFinish,
  isSaving,
}: ActionableNotesReviewPanelProps) {
  const visibleItems = notes.items.filter((item) => item.reviewStatus !== "removed");
  const reviewedItemCount = visibleItems.filter(
    (item) => item.reviewStatus === "accepted" || item.reviewStatus === "corrected",
  ).length;
  const isReviewClosed = notes.reviewedAt !== null;
  const reviewProgressPercentage =
    visibleItems.length === 0 ? 100 : Math.round((reviewedItemCount / visibleItems.length) * 100);

  return (
    <div className="space-y-6">
      <article className="rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm sm:p-8">
        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="secondary">Meeting brief</Badge>
          {notes.detectedLanguages.map((detectedLanguage) => (
            <Badge key={detectedLanguage} variant="outline">
              {detectedLanguage}
            </Badge>
          ))}
          {isReviewClosed && (
            <Badge className="border-emerald-200 bg-emerald-50 text-emerald-800">
              <CheckCircle2Icon aria-hidden="true" className="size-3.5" />
              Review complete
            </Badge>
          )}
        </div>
        <h2 className="mt-5 text-xl font-semibold tracking-tight">What happened</h2>
        <p className="mt-3 text-sm leading-7 text-neutral-700">{notes.summary}</p>
        <p className="mt-5 text-xs text-neutral-500">
          Generated by {notes.generationProvider}. AI-generated outcomes are proposals — confirm
          each one against its transcript evidence.
        </p>
        {notes.generationWarning && (
          <p
            role="status"
            className="mt-4 flex items-start gap-2.5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"
          >
            <TriangleAlertIcon aria-hidden="true" className="mt-0.5 size-4 shrink-0" />
            {notes.generationWarning}
          </p>
        )}
      </article>

      <section className="rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm sm:p-8">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-neutral-500">
              Review queue
            </p>
            <h2 className="mt-2 text-xl font-semibold tracking-tight">
              Outcomes worth carrying forward
            </h2>
          </div>
          {visibleItems.length > 0 && (
            <div className="min-w-40">
              <p className="text-right text-xs font-medium tabular-nums text-neutral-600">
                {reviewedItemCount} of {visibleItems.length} reviewed
              </p>
              <div
                role="progressbar"
                aria-valuenow={reviewProgressPercentage}
                aria-valuemin={0}
                aria-valuemax={100}
                aria-label="Review progress"
                className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-neutral-200"
              >
                <div
                  className="h-full rounded-full bg-neutral-950 transition-[width] duration-300"
                  style={{ width: `${reviewProgressPercentage}%` }}
                />
              </div>
            </div>
          )}
        </div>

        {visibleItems.length === 0 ? (
          <div className="mt-8 rounded-2xl border border-dashed border-neutral-300 p-8 text-center">
            <CheckIcon aria-hidden="true" className="mx-auto size-7 text-emerald-600" />
            <p className="mt-3 font-medium text-neutral-900">No actionable outcomes detected</p>
            <p className="mx-auto mt-1 max-w-sm text-sm text-neutral-500">
              MeetLoop found nothing it could evidence. The summary and the full transcript are
              still available below.
            </p>
          </div>
        ) : (
          <ul className="mt-6 space-y-3">
            {visibleItems.map((item) => (
              <ActionableNoteItemCard
                key={item.id}
                item={item}
                isSaving={isSaving}
                isReviewClosed={isReviewClosed}
                resolvableEvidenceChunkIds={resolvableEvidenceChunkIds}
                onUpdate={onUpdate}
              />
            ))}
          </ul>
        )}

        {!isReviewClosed && (
          <div className="mt-6 flex flex-wrap items-center justify-end gap-3">
            {reviewedItemCount < visibleItems.length && (
              <p className="text-xs text-neutral-500">
                {visibleItems.length - reviewedItemCount} outcome
                {visibleItems.length - reviewedItemCount === 1 ? "" : "s"} still unreviewed — you
                can finish anyway.
              </p>
            )}
            <Button disabled={isSaving} onClick={() => void onFinish()} className="h-10 rounded-xl">
              {isSaving ? (
                <LoaderCircleIcon aria-hidden="true" className="animate-spin" />
              ) : (
                <CheckIcon aria-hidden="true" />
              )}
              Finish review
            </Button>
          </div>
        )}
      </section>
    </div>
  );
}
